<?php
	require_once("common/common_constants.php");
	require_once("common/common_before_loading.php");
	require_once("common/common_start_session.php");
	require_once("bars/bar_header.php");
	require_once("bars/bar_navigation.php");
	require_once("bars/bar_page_list_all_robots.php");
	require_once("bars/bar_footer.php");
?>
